//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas_inventario
    {
        public int id { get; set; }
        public Nullable<int> id_citas { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public Nullable<int> cantidad_utilizada { get; set; }
    
        public virtual citas citas { get; set; }
        public virtual inventario_medico inventario_medico { get; set; }
    }
}
