//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citas()
        {
            this.citas_inventario = new HashSet<citas_inventario>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<int> id_historial_clinico { get; set; }
        public string estado { get; set; }
        public byte[] fecha_hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citas_inventario> citas_inventario { get; set; }
        public virtual historial_clinico historial_clinico { get; set; }
        public virtual personal personal { get; set; }
    }
}
