//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class departamento
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "#")]
        public Nullable<int> id_personal { get; set; }
        [Display(Name = "#")]
        public Nullable<int> id_paciente { get; set; }
        [Display(Name = "nombre del departamento")]
        public string nombre_departamento { get; set; }
        [Display(Name = "descripcion")]
        public string descripcion { get; set; }
    
        public virtual pacientes pacientes { get; set; }
        public virtual personal personal { get; set; }
    }
}
