//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_clinico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public historial_clinico()
        {
            this.citas = new HashSet<citas>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public byte[] fecha_registro_historial { get; set; }
        public string historial_enfermedades { get; set; }
        public string motivo_consulta { get; set; }
        public string diagnostico { get; set; }
        public string tratamiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citas> citas { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
