//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_laboral
    {
        public int id { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
    
        public virtual personal personal { get; set; }
    }
}
