//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespiteClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario_medico()
        {
            this.citas_inventario = new HashSet<citas_inventario>();
        }
    
        public int id { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public string stock { get; set; }
        public string MOQ { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public string proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citas_inventario> citas_inventario { get; set; }
    }
}
